BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBB XXXX XXX XXXX XXX
BBBBB BBBBBXXXXXBBBBBBBB
BBBBB BBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX
            XXXXXX
        XXXX gettext(u'Rango says!') XXXXX
        XXXXXXXXXXXXXXXXXXXX XX
         gettext(u'You visit: %(visit)s') SSS SSSSSS SSSSSSSSS
        XX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XX
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXX XX XXXXXX XX XXXX XXX XXXX XXX
        XXXXXXX XXXXXXXXXXXXXXX XXXXX XX X XXX XXXXXXXXXX XX XXXXXXXXXXXXXX

		XXXXXXX XX X XXXXXXXXXXX

		XXXXXXX XX XXXXXXX XXXXXXXXXXX
BBBBBBBB
