BBBBBBB BBBBBBBBBBB

BBBBB BBBBBXXX XXXXBBBBBBBB


BBBBB BBBBBBBBBB
BB BBBBBBBB

                XXXXX XXXXXXXXXXX  XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    BBBBBBBBBB
                    BBB BBBBBB BB BBBBBBBBBBBBBBBBBB
                        
                    BBBBBB

                    BBB BBBBB BB BBBBBBBBBBBBBBBBBBB
                        
                        XXXXX
                        XXXXX
                    BBBBBB

                XXXXX
            XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXX
            BBBB
            XXXXXXX XX XXXXXXXX XXXX XXX XXXXXXXXXX
        BBBBB


        BBBBBBBB